In [401]:
""" Index, Slice and Reshape Numpy Arrays """

' Index, Slice and Reshape Numpy Arrays '

In [402]:
""" from List to Arrays """

' from List to Arrays '

In [403]:
""" One dimensional list to array """
import numpy as np
data = [11, 22, 33, 44, 55, 66]
data = np.array(data)
print(f"data: {data}\n")
print(f"type of data: {type(data)}")

data: [11 22 33 44 55 66]

type of data: <class 'numpy.ndarray'>


In [404]:
""" Two dimensional list of lists to array """
data1 = [[11, 22],
         [33, 44],
         [55, 66]]
data1 = np.array(data1)
print(f"data1: {data1}\n")
print(f"type of data1: {type(data1)}")

data1: [[11 22]
 [33 44]
 [55 66]]

type of data1: <class 'numpy.ndarray'>


In [405]:
""" Array Indexing """

' Array Indexing '

In [406]:
""" One dimensional indexing """
print(f"data[0]: {data[0]}")
print(f"data[3]: {data[3]}")

data[0]: 11
data[3]: 44


In [407]:
print(f"data[-1]: {data[-1]}")
print(f"data[-3]: {data[-3]}")

data[-1]: 66
data[-3]: 44


In [408]:
""" Two dimensional indexing """
print(f"data1[0, 0]: {data1[0, 0]}")

data1[0, 0]: 11


In [409]:
# all items in the first row:
print(f"data1[0,]: {data1[0, ]}")

data1[0,]: [11 22]


In [410]:
""" Array Slicing """

' Array Slicing '

In [411]:
# The slice extends from the index and ends one item before the to index:
# data[from:to -1]

In [412]:
""" One dimensional slicing """
# access all data in an array dimension by 
# specifying the slice ‘:’ with no indexes
print(f"data[:]: {data[:]}")

data[:]: [11 22 33 44 55 66]


In [413]:
# The first item of the array can be sliced by specifying a slice 
# that starts at index 0 and ends at index 1 (one item before the to index).
print(f"data[0, 1]: {data[0: 1]}")

data[0, 1]: [11]


In [414]:
# We can also use negative indexes in slices. For example, we can slice 
# the last two items in the list by starting the slice at -2 (the second
# last item) and not specifying a to index; that takes the slice to the 
# end of the dimension.

print(f"data[-2:]: {data[-2:]}")

data[-2:]: [55 66]


In [415]:
""" Two dimensional slicing """

' Two dimensional slicing '

In [416]:
""" Split input and output features """

' Split input and output features '

In [417]:
# It is common to split your loaded data into input variables (X) and the 
# output variable (y). We can do this by slicing all rows and all columns
# up to, but before the last column, then separately indexing the last
# column. For the input features, we can select all rows and all columns except
# the last one by specifying : for in the rows index, and :-1 in the columns index.

# X = [:, :-1]

# For the output column, we can select all rows again using : and index just
# the last column by specifying the -1 index.

# y = [:, -1]

data2 = np.array([[11, 22, 33],
                  [44, 55, 66],
                  [77, 88, 99]])

X, y = data2[:, :-1], data2[:, -1]

In [418]:
print(f"X:\n{X}\n")

X:
[[11 22]
 [44 55]
 [77 88]]



In [419]:
print(f"y:\n{y}")

y:
[33 66 99]


In [420]:
""" Split train and test rows """

' Split train and test rows '

In [421]:
# It is common to split a loaded dataset into separate train and test sets. 
# This is a splitting of rows where some portion will be used to train the
# model and the remaining portion will be used to estimate the skill of the
# trained model. This would involve slicing all columns by specifying : in
# the second dimension index. The training dataset would be all rows from
# the beginning to the split point.

# train = data[:split, :]

# The test dataset would be all rows starting from the split point to 
# the end of the dimension.

# test[split:, :]

# Putting all of this together, we can split the dataset at the contrived 
# split point of 2.

split = 2
train , test = data2[:split, :], data2[split:, :]

In [422]:
print(f"train:\n{train}")

train:
[[11 22 33]
 [44 55 66]]


In [423]:
print(f"test:\n{test}")

test:
[[77 88 99]]


In [424]:
""" Array reshaping """

' Array reshaping '

In [425]:
""" Data Shape """

' Data Shape '

In [426]:
print(f"shape of data: {data.shape}")

shape of data: (6,)


In [427]:
print(f"shape of data2: {data2.shape}")

shape of data2: (3, 3)


In [428]:
print(f"Rows: {data2.shape[0]}")

Rows: 3


In [429]:
print(f"Columns: {data2.shape[1]}")

Columns: 3


In [430]:
""" Reshape 1D to 2D Array """

' Reshape 1D to 2D Array '

In [431]:
data_2d = data.reshape((data.shape[0], 1))

In [432]:
print(f"data_2d: {data_2d}")

data_2d: [[11]
 [22]
 [33]
 [44]
 [55]
 [66]]


In [433]:
print(f"shape of data_2d: {data_2d.shape}")

shape of data_2d: (6, 1)


In [434]:
""" Reshape 2D to 3D array """

' Reshape 2D to 3D array '

In [435]:
data_3d = data2.reshape(data2.shape[0], data2.shape[1], 1)

In [436]:
print(f"data_3d: {data_3d}")

data_3d: [[[11]
  [22]
  [33]]

 [[44]
  [55]
  [66]]

 [[77]
  [88]
  [99]]]


In [437]:
print(f"shape of data_3d: {data_3d.shape}")


shape of data_3d: (3, 3, 1)
