## Matrices and Matrix Arithmetic
### Defining a matrix:

In [17]:
from numpy import array

A = array([[1, 2, 3],
           [4, 5, 6]])
print(f"A: \n{A}")

A: 
[[1 2 3]
 [4 5 6]]


### Matrix Arithmetic
### Matrix Addition:

In [18]:
A = array([[1, 2, 3],
           [4, 5, 6]])
print(f"A: \n{A}\n")

B = array([[1, 2, 3],
           [4, 5, 6]])
print(f"B: \n{B}\n")

C = A + B
print(f"C: \n{C}")

A: 
[[1 2 3]
 [4 5 6]]

B: 
[[1 2 3]
 [4 5 6]]

C: 
[[ 2  4  6]
 [ 8 10 12]]


### Matrix Subtraction:

In [19]:
C = A - B
print(f"C: \n{C}")

C: 
[[0 0 0]
 [0 0 0]]


### Matrix Multiplication
### Hadamard Product:

In [20]:
C = A * B
print(f"C: \n{C}")

C: 
[[ 1  4  9]
 [16 25 36]]


### Matrix Division:

In [21]:
C = A / B
print(f"C: \n{C}")

C: 
[[1. 1. 1.]
 [1. 1. 1.]]


### Matrix-Matrix Multiplication
### Using dot() method:

In [22]:
A = array([[1, 2],
           [3, 4],
           [5, 6]])
print(f"A: \n{A}\n")

B = array([[1, 2],
           [3, 4]])
print(f"B: \n{B}\n")

# multiply matrices using dot method
C = A.dot(B)
print(f"C: \n{C}")

A: 
[[1 2]
 [3 4]
 [5 6]]

B: 
[[1 2]
 [3 4]]

C: 
[[ 7 10]
 [15 22]
 [23 34]]


### Using @ operand:

In [23]:
D = A @ B
print(f"D: \n{D}")

D: 
[[ 7 10]
 [15 22]
 [23 34]]


In [24]:
D = A @ B
print(f"D: \n{D}")

D: 
[[ 7 10]
 [15 22]
 [23 34]]


### Matrix-Vector Multiplication
### Using dot() method:

In [25]:
B = array([0.5, 0.5])
print(f"B vector: {B}")

C = A.dot(B)
print(f"C: {C}")


B vector: [0.5 0.5]
C: [1.5 3.5 5.5]


### Matrix-Scalar Multiplication

In [28]:
A = array([[1, 2],
           [3, 4],
           [5, 6]])
print(f"A: \n{A}\n")

b = 0.5
print(f"Scalar b: {b}\n")

C = A * b
print(f"C: \n{C}")


A: 
[[1 2]
 [3 4]
 [5 6]]

Scalar b: 0.5

C: 
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
