## Matrix Operations
### Transpose:

In [3]:
from numpy import array

A = array([[1, 2],
           [3, 4],
           [5, 6]])
print(f"A: \n{A}\n")

C = A.T
print(f"C: \n{C}")

A: 
[[1 2]
 [3 4]
 [5 6]]

C: 
[[1 3 5]
 [2 4 6]]
