## Tensors And Tensor Arithmetic
### Creating A Tensor:

In [5]:
from numpy import array

T = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

print(f"T.shape: {T.shape}\n")
print(T)

T.shape: (3, 3, 3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### Tensor Arithmetic
### Tensor Addition:

In [7]:
A = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])
print(f"A: \n{A}\n")

B = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])
print(f"B: \n{B}\n")

C = A + B
print(f"C: {C}")


A: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

B: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

C: [[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]
