## Introduction to Numpy Arrays

### Importing Numpy

In [81]:
import numpy as np

### Creating an array

In [82]:
l = [1.0, 2.0, 3.0]
a = np.array(l)

### Displaying array

In [83]:
print(f"a: {a}")

a: [1. 2. 3.]


### Functions to Create Arrays
### Empty:

In [84]:
b = np.empty([3, 3])
print(f"b: \n{b}")

b: 
[[6.94892619e-310 4.64915932e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.42092166e-322 4.64915946e-310]]


### Zeros:

In [85]:
c = np.zeros([3, 5])
print(f"c: \n{c}")

c: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones:

In [86]:
d = np.ones([5])
print(f"d: {d}")

d: [1. 1. 1. 1. 1.]


### Combining Arrays
### Vertical Stack:

In [87]:
a1 = np.array([1, 2, 3])
print(f"a1: {a1}\n")

a2 = np.array([4, 5, 6])
print(f"a2: {a2}")

a1: [1 2 3]

a2: [4 5 6]


In [88]:
a3 = np.vstack((a1, a2))
print(f"a3: \n{a3}\n")

print(f"a3.shape: {a3.shape}")

a3: 
[[1 2 3]
 [4 5 6]]

a3.shape: (2, 3)


### Horizontal Stack:

In [94]:
a4 = np.array([1, 2, 3])
print(f"a4: {a4}\n")

a5 = np.array([4, 5, 6])
print(f"a4: {a4}\n")


# create horizontal stack
a6 = np.hstack((a4, a5))
print(f"a6: {a6}\n")

print(f"a6.shape: {a6.shape}")


a4: [1 2 3]

a4: [1 2 3]

a6: [1 2 3 4 5 6]

a6.shape: (6,)
