In [214]:
""" Index, Slice and Reshape Numpy Arrays """

' Index, Slice and Reshape Numpy Arrays '

In [215]:
""" from List to Arrays """

' from List to Arrays '

In [216]:
""" One dimensional list to array """
import numpy as np
data = [11, 22, 33, 44, 55, 66]
data = np.array(data)
print(f"data: {data}\n")
print(f"type of data: {type(data)}")

data: [11 22 33 44 55 66]

type of data: <class 'numpy.ndarray'>


In [217]:
""" Two dimensional list of lists to array """
data1 = [[11, 22],
         [33, 44],
         [55, 66]]
data1 = np.array(data1)
print(f"data1: {data1}\n")
print(f"type of data1: {type(data1)}")

data1: [[11 22]
 [33 44]
 [55 66]]

type of data1: <class 'numpy.ndarray'>


In [218]:
""" Array Indexing """

' Array Indexing '

In [219]:
""" One dimensional indexing """
print(f"data[0]: {data[0]}")
print(f"data[3]: {data[3]}")

data[0]: 11
data[3]: 44


In [220]:
print(f"data[-1]: {data[-1]}")
print(f"data[-3]: {data[-3]}")

data[-1]: 66
data[-3]: 44


In [221]:
""" Two dimensional indexing """
print(f"data1[0, 0]: {data1[0, 0]}")

data1[0, 0]: 11


In [222]:
# all items in the first row:
print(f"data1[0,]: {data1[0, ]}")

data1[0,]: [11 22]


In [223]:
""" Array Slicing """

' Array Slicing '

In [224]:
# The slice extends from the index and ends one item before the to index:
# data[from:to -1]

In [225]:
""" One dimensional slicing """
# access all data in an array dimension by 
# specifying the slice ‘:’ with no indexes
print(f"data[:]: {data[:]}")

data[:]: [11 22 33 44 55 66]


In [226]:
# The first item of the array can be sliced by specifying a slice 
# that starts at index 0 and ends at index 1 (one item before the to index).
print(f"data[0, 1]: {data[0: 1]}")

data[0, 1]: [11]


In [227]:
# We can also use negative indexes in slices. For example, we can slice 
# the last two items in the list by starting the slice at -2 (the second
# last item) and not specifying a to index; that takes the slice to the 
# end of the dimension.

print(f"data[-2:]: {data[-2:]}")

data[-2:]: [55 66]


In [228]:
""" Two dimensional slicing """

' Two dimensional slicing '

In [229]:
""" Split input and output features """

' Split input and output features '

In [230]:
# It is common to split your loaded data into input variables (X) and the 
# output variable (y). We can do this by slicing all rows and all columns
# up to, but before the last column, then separately indexing the last
# column. For the input features, we can select all rows and all columns except
# the last one by specifying : for in the rows index, and :-1 in the columns index.

# X = [:, :-1]

# For the output column, we can select all rows again using : and index just
# the last column by specifying the -1 index.

# y = [:, -1]

data2 = np.array([[11, 22, 33],
                  [44, 55, 66],
                  [77, 88, 99]])

X, y = data2[:, :-1], data2[:, -1]

In [231]:
print(f"X:\n{X}\n")

X:
[[11 22]
 [44 55]
 [77 88]]



In [232]:
print(f"y:\n{y}")

y:
[33 66 99]


In [233]:
""" Split train and test rows """

' Split train and test rows '

In [234]:
# It is common to split a loaded dataset into separate train and test sets. 
# This is a splitting of rows where some portion will be used to train the
# model and the remaining portion will be used to estimate the skill of the
# trained model. This would involve slicing all columns by specifying : in
# the second dimension index. The training dataset would be all rows from
# the beginning to the split point.

# train = data[:split, :]

# The test dataset would be all rows starting from the split point to 
# the end of the dimension.

# test[split:, :]

# Putting all of this together, we can split the dataset at the contrived 
# split point of 2.

split = 2
train , test = data2[:split, :], data2[split:, :]

In [235]:
print(f"train:\n{train}")

train:
[[11 22 33]
 [44 55 66]]


In [236]:
print(f"test:\n{test}")


test:
[[77 88 99]]
