## Tensors And Tensor Arithmetic
### Creating A Tensor:

In [5]:
from numpy import array

T = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

print(f"T.shape: {T.shape}\n")
print(T)

T.shape: (3, 3, 3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### Tensor Arithmetic
### Tensor Addition:

In [7]:
A = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])
print(f"A: \n{A}\n")

B = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])
print(f"B: \n{B}\n")

C = A + B
print(f"C: {C}")


A: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

B: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

C: [[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


### Tensor Subtraction:

In [11]:
C = A - B
print(f"C: \n{C}")

C: 
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


### Tensor hadamard Product:

In [14]:
C = A * B
print(f" C (Hadamard Product of A and B):\n\n {C}")

 C (Hadamard Product of A and B):

 [[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]


### Tensor Division:

In [16]:
C = A / B
print(f"C(Tensor Division):\n\n {C}")

C(Tensor Division):

 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### Tensor Product:
### Using tensordot() method:
**First Example:**

In [19]:
from numpy import tensordot

# Example 1
A = array([1, 2])
print(f"A: {A}\n")

B = array([3, 4])
print(f"B: {B}\n")

C = tensordot(A, B, axes=0)
print(f"C:\n {C}")

A: [1 2]

B: [3 4]

C:
 [[3 4]
 [6 8]]


**Second Example:**

In [21]:
A = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])
print(f"A:\n {A}\n")

B = array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])
print(f"B:\n {B}\n")

C = tensordot(A, B, axes=0)
print(f"C:\n {C}")

A:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

B:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

C:
 [[[[[[  1   2   3]
     [  4   5   6]
     [  7   8   9]]

    [[ 10  11  12]
     [ 13  14  15]
     [ 16  17  18]]

    [[ 19  20  21]
     [ 22  23  24]
     [ 25  26  27]]]


   [[[  2   4   6]
     [  8  10  12]
     [ 14  16  18]]

    [[ 20  22  24]
     [ 26  28  30]
     [ 32  34  36]]

    [[ 38  40  42]
     [ 44  46  48]
     [ 50  52  54]]]


   [[[  3   6   9]
     [ 12  15  18]
     [ 21  24  27]]

    [[ 30  33  36]
     [ 39  42  45]
     [ 48  51  54]]

    [[ 57  60  63]
     [ 66  69  72]
     [ 75  78  81]]]]



  [[[[  4   8  12]
     [ 16  20  24]
     [ 28  32  36]]

    [[ 40  44  48]
     [ 52  56  60]
     [ 64  68  72]]

    [[ 76  80  84]
     [ 88  92  96]
     [100 104 108]]]


   [[[  5  10  15]
   