## Type of Matrices
### Triangular Matrix:

In [2]:
from numpy import array
from numpy import tril
from numpy import triu

M = array([[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]])
print(f"M: \n{M}")

lower = tril(M)
print(f"lower: \n{lower}\n")

upper = triu(M)
print(f"upper: \n{upper}")

M: 
[[1 2 3]
 [1 2 3]
 [1 2 3]]
lower: 
[[1 0 0]
 [1 2 0]
 [1 2 3]]

upper: 
[[1 2 3]
 [0 2 3]
 [0 0 3]]
