## Type of Matrices
### Triangular Matrix:

In [3]:
from numpy import array
from numpy import tril
from numpy import triu

M = array([[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]])
print(f"M: \n{M}\n")

lower = tril(M)
print(f"lower: \n{lower}\n")

upper = triu(M)
print(f"upper: \n{upper}")

M: 
[[1 2 3]
 [1 2 3]
 [1 2 3]]

lower: 
[[1 0 0]
 [1 2 0]
 [1 2 3]]

upper: 
[[1 2 3]
 [0 2 3]
 [0 0 3]]


### Diagonal Matrix:

In [7]:
from numpy import diag

d = diag(M)
print(f"diag(M): {d}\n")

D = diag(d)
print(f"Diagonal Matrix: \n{D}")

diag(M): [1 2 3]

Diagonal Matrix: 
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Identity Matrix:

In [11]:
from numpy import identity

I = identity(3)
print(f"I: \n{I}")

I: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Orthogonal Matrix:

In [13]:
from numpy.linalg import inv

Q = array([[1, 0],
           [0, -1]])
print(f"Q: \n{Q}\n")

# inverse equivalence
V = inv(Q)
print(f"Q.T: \n{Q.T}\n")
print(f"V: \n{V}\n")

# identity equivalence
I = Q.dot(Q.T)
print(f"I: \n{I}")

Q: 
[[ 1  0]
 [ 0 -1]]

Q.T: 
[[ 1  0]
 [ 0 -1]]

V: 
[[ 1.  0.]
 [-0. -1.]]

I: 
[[1 0]
 [0 1]]
