In [18]:
""" Introduction to Numpy Arrays """

' Introduction to Numpy Arrays '

In [19]:
# importing numpy
import numpy as np

In [20]:
# create a array
l = [1.0, 2.0, 3.0]
a = np.array(l)

In [21]:
# display array
print(f"a: {a}")

a: [1. 2. 3.]


In [22]:
# display array shape
print(f"a.shape: {a.shape}")

a.shape: (3,)


In [23]:
# display array data type
print(f"a.dtype: {a.dtype}")

a.dtype: float64


In [24]:
""" Functions to create arrays """

' Functions to create arrays '

In [25]:
""" Empty """
b = np.empty([3, 3])
print(f"b: {b}")

b: [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [6.37344683e-322 4.66882530e-310 6.90493079e-310]
 [0.00000000e+000 0.00000000e+000 6.90492891e-310]]


In [26]:
""" Zeros """
c = np.zeros([3, 5])
print(f"c: {c}")

c: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
""" Ones """
d = np.ones([5])
print(f"d: {d}")


d: [1. 1. 1. 1. 1.]
