## Sparse Matrices
### Sparse Matrices in Python:

In [2]:
from numpy import array
from scipy.sparse import csr_matrix

A = array([[1, 0, 0, 1, 0, 0],
           [0, 0, 2, 0, 0, 1],
           [0, 0, 0, 2, 0, 0]])
print(f"A: \n{A}\n")

# convert to sparse matrix
S = csr_matrix(A)
print(f"S: \n{S}\n")

# reconstruct dense matrix
B = S.todense()
print(f"B: \n{B}")

A: 
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]

S: 
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2

B: 
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


### Sparsity:

In [3]:
from numpy import count_nonzero

sparsity = 1.0 - count_nonzero(A) / A.size
print(f"Sparsity: {sparsity}")

Sparsity: 0.7222222222222222
