## Matrix Operations
### Transpose:

In [4]:
from numpy import array

A = array([[1, 2],
           [3, 4],
           [5, 6]])
print(f"A: \n{A}\n")

C = A.T
print(f"C: \n{C}")

A: 
[[1 2]
 [3 4]
 [5 6]]

C: 
[[1 3 5]
 [2 4 6]]


### Inverse:

In [8]:
from numpy.linalg import inv

A = array([[1.0, 2.0],
           [3.0, 4.0]])
print(f"A: \n{A}\n")

B = inv(A)
print(f"B: \n{B}\n")

I = A.dot(B)
print(f"I: \n{I}")

A: 
[[1. 2.]
 [3. 4.]]

B: 
[[-2.   1. ]
 [ 1.5 -0.5]]

I: 
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### Trace:

In [10]:
from numpy import trace

A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

B = trace(A)
print(f"B: {B}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B: 15
