In [29]:
""" Introduction to Numpy Arrays """

' Introduction to Numpy Arrays '

In [30]:
# importing numpy
import numpy as np

In [31]:
# create a array
l = [1.0, 2.0, 3.0]
a = np.array(l)

In [32]:
# display array
print(f"a: {a}")

a: [1. 2. 3.]


In [33]:
# display array shape
print(f"a.shape: {a.shape}")

a.shape: (3,)


In [34]:
# display array data type
print(f"a.dtype: {a.dtype}")

a.dtype: float64


In [35]:
""" Functions to create arrays """

' Functions to create arrays '

In [36]:
""" Empty """
b = np.empty([3, 3])
print(f"b: {b}")

b: [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [6.37344683e-322 4.66882530e-310 6.90493079e-310]
 [0.00000000e+000 0.00000000e+000 6.90492891e-310]]


In [37]:
""" Zeros """
c = np.zeros([3, 5])
print(f"c: {c}")

c: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
""" Ones """
d = np.ones([5])
print(f"d: {d}")

d: [1. 1. 1. 1. 1.]


In [39]:
""" Combining Arrays """

' Combining Arrays '

In [40]:
# vertical stack
a1 = np.array([1, 2, 3])
print(f"a1: {a1}")

a1: [1 2 3]


In [41]:
a2 = np.array([4, 5, 6])
print(f"a2: {a2}")

a2: [4 5 6]


In [42]:
a3 = np.vstack((a1, a2))
print(f"a3: {a3}")

a3: [[1 2 3]
 [4 5 6]]


In [43]:
print(f"a3.shape: {a3.shape}")

a3.shape: (2, 3)


In [44]:
# Horizontal stack
a4 = np.array([1, 2, 3])
print(f"a4: {a4}")

a4: [1 2 3]


In [45]:
a5 = np.array([4, 5, 6])
print(f"a5: {a5}")

a5: [4 5 6]


In [46]:
# create horizontal stack
a6 = np.hstack((a4, a5))
print(f"a6: {a6}")

a6: [1 2 3 4 5 6]


In [47]:
print(f"a6.shape: {a6.shape}")


a6.shape: (6,)
