## Matrices and Matrix Arithmetic
### Defining a matrix:

In [1]:
from numpy import array

A = array([[1, 2, 3],
           [4, 5, 6]])
print(f"A: \n{A}")

A: 
[[1 2 3]
 [4 5 6]]


### Matrix Arithmetic
### Matrix Addition:

In [4]:
A = array([[1, 2, 3],
           [4, 5, 6]])
print(f"A: \n{A}\n")

B = array([[1, 2, 3],
           [4, 5, 6]])
print(f"B: \n{B}\n")

C = A + B
print(f"C: \n{C}")

A: 
[[1 2 3]
 [4 5 6]]

B: 
[[1 2 3]
 [4 5 6]]

C: 
[[ 2  4  6]
 [ 8 10 12]]


### Matrix Subtraction:

In [5]:
C = A - B
print(f"C: \n{C}")


C: 
[[0 0 0]
 [0 0 0]]
