In [12]:
""" Numpy Array Broadcasting """

' Numpy Array Broadcasting '

In [13]:
"Scalar and one dimensional array"

# broadcasting scalar to one-dimensional array
import numpy as np

a = np.array([1, 2, 3])
print(f"a = {a}")

# define scalar
b = 2
print(f"b = {b}")

# broadcast
c = a + b
print(f"c = {c}")

a = [1 2 3]
b = 2
c = [3 4 5]


In [14]:
"Scalar and two-dimensional array"

# broadcast scalar to two-dimensional array
d = np.array([[1, 2, 3],
              [1, 2, 3]])
print(f"d = {d}\n")

#define scalar
e = 2
print(f"e = {e}\n")

# broadcast
f = d + e
print(f"f = {f}")

d = [[1 2 3]
 [1 2 3]]

e = 2

f = [[3 4 5]
 [3 4 5]]


In [15]:
"""One dimensional and two dimensional arrays"""

# broadcast one-dimensional array to two-dimensional array
A = np.array([[1, 2, 3],
              [1, 2, 3]])
print(f"A = {A}\n")

b = np.array([1, 2, 3])
print(f"b = {b}\n")

# broadcast
C = A + b
print(f"C = {C}")

A = [[1 2 3]
 [1 2 3]]

b = [1 2 3]

C = [[2 4 6]
 [2 4 6]]


In [16]:

""" Limitations of broadcasting """


# broadcasting error
print(f"Shape of A = {A.shape}")

b = np.array([1, 2])
print(f"Shape of b = {b.shape}")

C = A + b
print(C)


Shape of A = (2, 3)
Shape of b = (2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 