## Introduction to Multivariate Statistics
### Expected Value and Mean:

In probability, the average value of some random variable $X$ is called the expected value or the
expectation. The expected value uses the notation E with square brackets around the name of
the variable; for example:

$$E[X]$$

It is calculated as the probability weighted sum of values that can be drawn.

$$E[X] =  \sum x_{1} \times p_{1},x_{2} \times p_{2} ... x_{n} \times p_{n}$$

the expected value can be calculated as the sum of all values multiplied by the reciprocal of the number of values.

$$E[X] =  \frac{1}{n} \times \sum x_{1},x_{2},x_{3}, ... , x_{n}$$

In the abstract, the mean is denoted by the lower case Greek letter mu μ and is calculated from the sample of observations, rather than all possible values.

$$\mu = \frac{1}{n} \times \sum x_{1},x_{2},x_{3}, ... , x_{n}$$

or , writen more compactly:

$$\mu = P(x) \times \sum x$$

Where $x$ is the vector of observations and $P(x)$ is the calculated probability for each value. When calculated for a specific variable, such as $x$, the mean is denoted as a lower case variable name with a line above, called x-bar:

$$\overline{x} =  \frac{1}{n} \times  \sum_{i=1}^n x_{i}$$


In [2]:
# vector mean
from numpy import array
from numpy import mean

# defining an array(vector)
v = array([1, 2, 3, 4, 5, 6])
print(f"v: {v}\n")

# calculating mean
result = mean(v)
print(f"result: {result}")

v: [1 2 3 4 5 6]

result: 3.5


The mean function can calculate the row or column means of a matrix by specifying the
axis argument and the value 0 or 1 respectively. The example below defines a $2 \times 6$ matrix and
calculates both column and row means.

In [3]:
# matrix mean
from numpy import array
from numpy import mean

# defining an array(matrix)
M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])
print(f"M: \n{M}\n")

# column means
col_mean = mean(M, axis=0)
print(f"col_mean: {col_mean}\n")

# row means
row_mean = mean(M, axis=1)
print(f"row_mean: {row_mean}")

M: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

col_mean: [1. 2. 3. 4. 5. 6.]

row_mean: [3.5 3.5]


### Variance and Standard Deviation:

$$Var[X]$$

$$Var[X] = E[(X - E[X])^2]$$

$$Var[X] = \sum p(x_{1}) \times (x_{1} - E[X])^2,p(x_{2}) \times (x_{2} - E[X])^2, ... , p(x_{n}) \times (x_{n} - E[X])^2$$

$$Va[X] =  \frac{1}{n} \times \sum (x_{1} - E[X])^2,(x_{2} - E[X])^2, ..., (x_{n} - E[X])^2$$

$$ \sigma ^2 =  \frac{1}{n - 1} \times  \sum_{i=1}^n (x_{i} - \mu)^2$$

In [4]:
# vector variance
from numpy import array
from numpy import var

# defining a vector
v = array([1, 2, 3, 4, 5, 6])
print(f"v: {v}\n")

# calculating variance
result = var(v, ddof=1)
print(f"result: {result}")

v: [1 2 3 4 5 6]

result: 3.5


In [5]:
# matrix variance
from numpy import array
from numpy import var

# defining an array(matrix)
M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])
print(f"M: \n{M}\n")

# column variances
col_var = var(M, ddof=1, axis=0)
print(f"col_var: {col_var}")

# row variances
row_var = var(M, ddof=1, axis=1)
print(f"row_var: {row_var}")

M: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

col_var: [0. 0. 0. 0. 0. 0.]
row_var: [3.5 3.5]


In [6]:
# matrix standard deviation
from numpy import array
from numpy import std

# defining an array(matrix)
M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])
print(f"M: \n{M}\n")

# column standard deviations
col_std = std(M, ddof=1, axis=0)
print(f"col_std: {col_std}\n")

# row standard deviation
row_std = std(M, ddof=1, axis=1)
print(f"row_std: {row_std}\n")

M: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

col_std: [0. 0. 0. 0. 0. 0.]

row_std: [1.87082869 1.87082869]



In [7]:
# vector covariance
from numpy import array
from numpy import cov

# defining first vector
x = array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"x: {x}\n")

# defining second vector
y = array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"y: {y}\n")

# calculating variance
Sigma = cov(x, y)[0, 1]
print(f"Sigma: {Sigma}")

x: [1 2 3 4 5 6 7 8 9]

y: [1 2 3 4 5 6 7 8 9]

Sigma: 7.5


In [8]:
# vector correlation
from numpy import array
from numpy import corrcoef

# defining first vector
x = array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"x: {x}\n")

# defining second vector
y = array([9, 8, 7, 6, 5, 4, 3, 2, 1])
print(f"y: {y}\n")

# calculating correlation
corr = corrcoef(x, y)[0, 1]
print(f"corr: {corr}")


x: [1 2 3 4 5 6 7 8 9]

y: [9 8 7 6 5 4 3 2 1]

corr: -1.0


In [9]:
# covariance matrix
from numpy import array
from numpy import cov

# defining matrix of obzervations
X = array([
    [1, 5, 8],
    [3, 5, 11],
    [2, 4, 9],
    [3, 6, 10],
    [1, 5, 10]
])
print(f"X: \n{X}\n")

# calculating covariance matrix
Sigma = cov(X.T)
print(f"Sigma: \n{Sigma}\n")


X: 
[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]

Sigma: 
[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]

