## Index, Slice and Reshape Numpy Arrays
### From List to Arrays
### One dimensional list to array:

In [210]:
import numpy as np

data = [11, 22, 33, 44, 55, 66]
data = np.array(data)

print(f"data: {data}\n")
print(f"type of data: {type(data)}")

data: [11 22 33 44 55 66]

type of data: <class 'numpy.ndarray'>


### Two dimensional list of lists to array:

In [211]:
data1 = [[11, 22],
         [33, 44],
         [55, 66]]
data1 = np.array(data1)

print(f"data1: \n{data1}\n")
print(f"type of data1: {type(data1)}")

data1: 
[[11 22]
 [33 44]
 [55 66]]

type of data1: <class 'numpy.ndarray'>


## Array Indexing
### One dimensional indexing:

In [212]:
print(f"data[0]: {data[0]}")
print(f"data[3]: {data[3]}")

print(f"data[-1]: {data[-1]}")
print(f"data[-3]: {data[-3]}")

data[0]: 11
data[3]: 44
data[-1]: 66
data[-3]: 44


### Two dimensional indexing:

In [213]:
print(f"data1[0, 0]: {data1[0, 0]}")

data1[0, 0]: 11


**All items in the first row:**

In [214]:
print(f"data1[0,]: {data1[0, ]}")

data1[0,]: [11 22]


## Array Slicing

**The slice extends from the index and ends one item before the to index:**

**data[from:to -1]**
### One dimensional slicing:
access all data in an array dimension by specifying the slice
‘:’ with no indexes:

In [215]:
print(f"data[:]: {data[:]}")

data[:]: [11 22 33 44 55 66]


The first item of the array can be sliced by specifying a slice that
starts at index 0 and ends at index 1 (one item before the to index):

In [216]:
print(f"data[0, 1]: {data[0: 1]}")

data[0, 1]: [11]


### Split input and output features:
It is common to split your loaded data into input variables (X) and the 
output variable (y). We can do this by slicing all rows and all columns
up to, but before the last column, then separately indexing the last
column. For the input features, we can select all rows and all columns
except the last one by specifying : for in the rows index, and :-1 in 
the columns index.

X = [:, :-1]

For the output column, we can select all rows again using : and index just
the last column by specifying the -1 index.

y = [:, -1]

In [217]:
data2 = np.array([[11, 22, 33],
                  [44, 55, 66],
                  [77, 88, 99]])

X, y = data2[:, :-1], data2[:, -1]

print(f"X:\n{X}\n")

print(f"y:\n{y}")

X:
[[11 22]
 [44 55]
 [77 88]]

y:
[33 66 99]


### Split train and test rows:
It is common to split a loaded dataset into separate train and test sets. 
This is a splitting of rows where some portion will be used to train the
model and the remaining portion will be used to estimate the skill of the
trained model. This would involve slicing all columns by specifying : in
the second dimension index. The training dataset would be all rows from
the beginning to the split point.

train = data[:split, :]

The test dataset would be all rows starting from the split point to 
the end of the dimension.

test[split:, :]

Putting all of this together, we can split the dataset at the contrived 
split point of 2.

In [218]:
split = 2
train , test = data2[:split, :], data2[split:, :]

print(f"train: \n{train}\n")
print(f"test: \n{test}")

train: 
[[11 22 33]
 [44 55 66]]

test: 
[[77 88 99]]


## Array reshaping
### Data Shape:

In [219]:
print(f"shape of data: {data.shape}")


print(f"shape of data2: {data2.shape}")

print(f"Rows: {data2.shape[0]}")

print(f"Columns: {data2.shape[1]}")

shape of data: (6,)
shape of data2: (3, 3)
Rows: 3
Columns: 3


### Reshape 1D to 2D Array:

In [220]:
data_2d = data.reshape((data.shape[0], 1))
print(f"data_2d: \n{data_2d}\n")
print(f"shape of data_2: {data_2d.shape}")

data_2d: 
[[11]
 [22]
 [33]
 [44]
 [55]
 [66]]

shape of data_2: (6, 1)


### Reshape 2D to 3D Array:

In [221]:
data_3d = data2.reshape(data2.shape[0], data2.shape[1], 1)
print(f"data_3d: \n{data_3d}\n")
print(f"shape of data_3d: {data_3d.shape}")


data_3d: 
[[[11]
  [22]
  [33]]

 [[44]
  [55]
  [66]]

 [[77]
  [88]
  [99]]]

shape of data_3d: (3, 3, 1)
