## Singular Value Decomposition
### What is the singular value decomposition?

The Singular-Value Decomposition, or SVD for short, is a matrix
decomposition method for reducing a matrix to its constituent parts
in order to make certain subsequent matrix calculations simpler. For
the case of simplicity we will focus on the SVD for real-valued matrices
and ignore the case for complex numbers.
    

$$A = U . \Sigma . V^{T}$$


Where $A$ is the real $n \times m$ matrix that we wish to decompose, $U$ is an
$m \times m$ matrix, $\Sigma$ represented by the uppercase Greek letter sigma)
is an $m \times n$ diagonal matrix, and $V^{T}$ is the $V$ transpose of an 
$n \times n$ matrix where $T$ is a superscript.

### Calculate Singular-Value Decomposition:

In [24]:
from numpy import array
from scipy.linalg import svd

# defining a matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(f"A: \n{A}\n")

# factorizing
U, s, V = svd(A)
print(f"U: \n{U}\n")
print(f"s: {s}\n")
print(f"V: \n{V}\n")

A: 
[[1 2]
 [3 4]
 [5 6]]

U: 
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

s: [9.52551809 0.51430058]

V: 
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]



### Reconstruct Matrix:

The original matrix can be reconstructed from the $U$ , $\Sigma$ and $V^{T}$ elements.
The $U$, $s$, and $V$ elements returned from the $svd()$ cannot be multiplied directly.
The $s$ vector must be converted into a diagonal matrix using the $diag()$ function.
By default, this function will create a square matrix that is $m \times m$, relative to
our original matrix. This causes a problem as the size of the matrices do not fit the 
rules of matrix multiplication, where the number of columns in a matrix must match the
number of rows in the subsequent matrix. After creating the square $\Sigma$ diagonal matrix,
the sizes of the matrices are relative to the original $n \times m$ matrix that we are
decomposing, as follows:

$$U(m \times m).\Sigma(m \times m). V^{T}(n \times n)$$

Where, in fact, we require:

$$U(m \times m).\Sigma(m \times n). V^{T}(n \times n)$$

We can achieve this by creating a new $\Sigma$ matrix of all zero values that is $m \times n$ (e.g. more
rows) and populate the first $n \times n$ part of the matrix with the square diagonal matrix calculated
via $diag()$.

In [32]:
# reconstructing rectangular matrix fro svd

from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

# defining a matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(f"A: \n{A}\n")

# factorizing
U, s, V = svd(A)

# creating m*n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

# populate Sigma with n*n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)

# reconstructing matrix
B = U.dot(Sigma.dot(V))
print(f"B: \n{B}")

A: 
[[1 2]
 [3 4]
 [5 6]]

B: 
[[1. 2.]
 [3. 4.]
 [5. 6.]]
