## Matrix Operations
### Transpose:

In [4]:
from numpy import array

A = array([[1, 2],
           [3, 4],
           [5, 6]])
print(f"A: \n{A}\n")

C = A.T
print(f"C: \n{C}")

A: 
[[1 2]
 [3 4]
 [5 6]]

C: 
[[1 3 5]
 [2 4 6]]


### Inverse:

In [8]:
from numpy.linalg import inv

A = array([[1.0, 2.0],
           [3.0, 4.0]])
print(f"A: \n{A}\n")

B = inv(A)
print(f"B: \n{B}\n")

I = A.dot(B)
print(f"I: \n{I}")

A: 
[[1. 2.]
 [3. 4.]]

B: 
[[-2.   1. ]
 [ 1.5 -0.5]]

I: 
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### Trace:

In [10]:
from numpy import trace

A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

B = trace(A)
print(f"B: {B}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B: 15


### Determinant:

In [11]:
from numpy.linalg import det

B = det(A)
print(f"determinant: {B}")

determinant: -9.51619735392994e-16


## Rank
### Vector Rank:

In [14]:
from numpy.linalg import matrix_rank

v1 = array([1, 2, 3])
print(f"v1: {v1}\n")

v1r = matrix_rank(v1)
print(f"rank of v1: {v1r}\n")

v2 = array([0, 0, 0, 0, 0])
print(f"v2: {v2}\n")

v2r = matrix_rank(v2)
print(f"rank of v2: {v2r}")

v1: [1 2 3]

rank of v1: 1

v2: [0 0 0 0 0]

rank of v2: 0


### Matrix Rank:
**Rank 0:**

In [21]:
# rank 0
M0 = array([[0, 0],
            [0, 0]])
print(f"M0: \n{M0}\n")

m0r = matrix_rank(M0)
print(f"rank of M0: {m0r}\n")

M0: 
[[0 0]
 [0 0]]

rank of M0: 0



**Rank 1:**

In [23]:
# rank 1
M1 = array([[1, 2],
            [1, 2]])
print(f"M1: {M1}\n")

m1r = matrix_rank(M1)
print(f"rank of M1: {m1r}\n")

M1: [[1 2]
 [1 2]]

rank of M1: 1



**Rank 2:**

In [26]:
# rank 2
M2 = array([[1, 2],
            [3, 4]])
print(f"M2: \n{M2}\n")

m2r = matrix_rank(M2)
print(f"rank of M2: {m2r}")

M2: 
[[1 2]
 [3 4]]

rank of M2: 2
