## Matrix Decompositions
### LU Decomposition:
    The LU decomposition is for square matrices and decomposes a
    matrix into L and U components.
    
        A = L.U
    
    The LU decomposition is found using an iterative numerical
    process and can fail for those matrices that cannot be decomposed
    or decomposed easily. A variation of this decomposition that is
    numerically more stable to solve in practice is called the LUP
    decomposition, or the LU decomposition with partial pivoting.
    
        A = L . U. P

In [2]:
from numpy import array
from scipy.linalg import lu

# define a square matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

# factorize
P, L, U = lu(A)
print(f"P:\n {P}\n")
print(f"L:\n {L}\n")
print(f"U:\n {U}\n")

# reconstruct
B = P.dot(L).dot(U)
print(f"B:\n {B}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L:
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

U:
 [[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

B:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
