## Eigen Decomposition
### Calculation of Eigendecomposition:
    An eigendecomposition is calculated on a square matrix using an efficient
    iterative algorithm, of which we will not go into the details. Often an 
    eigenvalue is found first, then an eigenvector is found to solve the 
    equation as a set of coefficients.

In [5]:
from numpy import array
from numpy.linalg import eig

# define a square matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

#factorize
values, vectors = eig(A)
print(f"values: {values}\n")
print(f"vectors: \n{vectors}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

values: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

vectors: 
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Confirm an Eigenvalue and Eigenvector:
    The eigenvectors are returned as a matrix with the same dimensions as the 
    parent matrix, where each column is an eigenvector, e.g. the first 
    eigenvector is vectors[:, 0]. Eigenvalues are returned as a list, where
    value indices in the returned array are paired with eigenvectors by 
    column index, e.g. the first eigenvalue at values[0] is paired with the 
    first eigenvector at vectors[:, 0].

In [7]:
from numpy import array
from numpy.linalg import eig

A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

# factorize
values, vectors = eig(A)

# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(f"B: {B}\n")

C = vectors[:, 0] * values[0]
print(f"C: {C}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B: [ -3.73863537  -8.46653421 -13.19443305]

C: [ -3.73863537  -8.46653421 -13.19443305]
