## Singular Value Decomposition
### What is the singular value decomposition?

The Singular-Value Decomposition, or SVD for short, is a matrix
decomposition method for reducing a matrix to its constituent parts
in order to make certain subsequent matrix calculations simpler. For
the case of simplicity we will focus on the SVD for real-valued matrices
and ignore the case for complex numbers.
    

$$A = U . \Sigma . V^{T}$$


Where $A$ is the real $n \times m$ matrix that we wish to decompose, $U$ is an
$m \times m$ matrix, $\Sigma$ represented by the uppercase Greek letter sigma)
is an $m \times n$ diagonal matrix, and $V^{T}$ is the $V$ transpose of an 
$n \times n$ matrix where $T$ is a superscript.

### Calculate Singular-Value Decomposition:

In [22]:
from numpy import array
from scipy.linalg import svd

# defining a matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(f"A: \n{A}\n")

# factorizing
U, s, V = svd(A)
print(f"U: \n{U}\n")
print(f"s: {s}\n")
print(f"V: \n{V}\n")

A: 
[[1 2]
 [3 4]
 [5 6]]

U: 
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

s: [9.52551809 0.51430058]

V: 
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

