## Matrix Decompositions
### LU Decomposition:
    The LU decomposition is for square matrices and decomposes a
    matrix into L and U components.
    
        A = L.U
    
    The LU decomposition is found using an iterative numerical
    process and can fail for those matrices that cannot be decomposed
    or decomposed easily. A variation of this decomposition that is
    numerically more stable to solve in practice is called the LUP
    decomposition, or the LU decomposition with partial pivoting.
    
        A = L . U. P

In [3]:
from numpy import array
from scipy.linalg import lu

# define a square matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

# factorize
P, L, U = lu(A)
print(f"P:\n {P}\n")
print(f"L:\n {L}\n")
print(f"U:\n {U}\n")

# reconstruct
B = P.dot(L).dot(U)
print(f"B:\n {B}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L:
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

U:
 [[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

B:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### QR Decomposition:
    The QR decomposition is for n × m matrices (not limited to
    square matrices) and decomposes a matrix into Q and R components.
    
    A = Q . R

In [5]:
from numpy.linalg import qr

# define rectangular matrix
A = array([[1, 2],
           [3, 4],
           [5, 6]])
print(f"A: \n{A}\n")

Q, R = qr(A, "complete")
print(f"Q: \n{Q}\n")
print(f"R: \n{R}\n")

# reconstruct
B = Q.dot(R)
print(f"B: \n{B}")

A: 
[[1 2]
 [3 4]
 [5 6]]

Q: 
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]

R: 
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

B: 
[[1. 2.]
 [3. 4.]
 [5. 6.]]


### Cholosky Decomposition:
    The Cholesky decomposition is for square symmetric matrices where
    all values are greater than zero, so-called positive definite matrices.
    For our interests in machine learning, we will focus on the Cholesky
    decomposition for real-valued matrices and ignore the cases when working
    with complex numbers. The decomposition is defined as follows:
    
    A = L . L**T

In [7]:
from numpy.linalg import cholesky

# define a symmetrical matrix
A = array([[2, 1, 1],
           [1, 2, 1],
           [1, 1, 2]])
print(f"A: \n{A}\n")

# factorize
L = cholesky(A)
print(f"L: \n{L}\n")

# reconstruct
B = L.dot(L.T)
print(f"B: \n{B}")

A: 
[[2 1 1]
 [1 2 1]
 [1 1 2]]

L: 
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]

B: 
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
