In [5]:
""" Introduction To Multivariate Statistics """

' Introduction To Multivariate Statistics '

In [6]:
# vector mean
from numpy import array
from numpy import mean

# defining an array(vector)
v = array([1, 2, 3, 4, 5, 6])
print(f"v: {v}\n")

# calculating mean
result = mean(v)
print(f"result: {result}")

v: [1 2 3 4 5 6]

result: 3.5


In [10]:
# matrix mean
from numpy import array
from numpy import mean

# defining an array(matrix)
M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])
print(f"M: \n{M}\n")

# column means
col_mean = mean(M, axis=0)
print(f"col_mean: {col_mean}\n")

# row means
row_mean = mean(M, axis=1)
print(f"row_mean: {row_mean}")

M: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

col_mean: [1. 2. 3. 4. 5. 6.]

row_mean: [3.5 3.5]


In [12]:
# vector variance
from numpy import array
from numpy import var

# defining a vector
v = array([1, 2, 3, 4, 5, 6])
print(f"v: {v}\n")

# calculating variance
result = var(v, ddof=1)
print(f"result: {result}")

v: [1 2 3 4 5 6]

result: 3.5


In [15]:
# matrix variance
from numpy import array
from numpy import var

# defining an array(matrix)
M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])
print(f"M: \n{M}\n")

# column variances
col_var = var(M, ddof=1, axis=0)
print(f"col_var: {col_var}")

# row variances
row_var = var(M, ddof=1, axis=1)
print(f"row_var: {row_var}")

M: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

col_var: [0. 0. 0. 0. 0. 0.]
row_var: [3.5 3.5]


In [20]:
# matrix standard deviation
from numpy import array
from numpy import std

# defining an array(matrix)
M = array([
    [1, 2, 3, 4, 5, 6],
    [1, 2, 3, 4, 5, 6]
])
print(f"M: \n{M}\n")

# column standard deviations
col_std = std(M, ddof=1, axis=0)
print(f"col_std: {col_std}\n")

# row standard deviation
row_std = std(M, ddof=1, axis=1)
print(f"row_std: {row_std}\n")

M: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

col_std: [0. 0. 0. 0. 0. 0.]

row_std: [1.87082869 1.87082869]

